version = 0.1

[default]

[default.deploy]

[default.deploy.parameters]
stack_name = "s3-md5-hash"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-20juh9o5jcwv"
s3_prefix = "s3-md5-hash"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "eventSourceBucket=\"encode-processing-v060921\""
profile = "encode-test"

[test]

[test.deploy]

[test.deploy.parameters]
stack_name = "s3-md5-hash-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-20juh9o5jcwv"
s3_prefix = "s3-md5-hash-test"
region = "us-west-2"
profile = "encode-test"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "eventSourceBucket=\"s3-md5-hash-test\""
