---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3-md5-hash

  Sample SAM Template for s3-md5-hash

Resources:
  S3MD5HashStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/s3_md5_hash.asl.json
      DefinitionSubstitutions:
        InitialMD5HashArn: !GetAtt InitialMD5Hash.Arn
        IntermediateMD5HashArn: !GetAtt IntermediateMD5Hash.Arn
        PutObjectTaggingArn: !GetAtt PutObjectTagging.Arn
      # Events:
      #   EBRule:
      #     Type: EventBridgeRule
      #     Properties:
      #       Pattern:
      #         source: aws.s3
      #         detail:
      #           state:
      #             - terminated
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref InitialMD5Hash
        - LambdaInvokePolicy:
            FunctionName: !Ref IntermediateMD5Hash
        - LambdaInvokePolicy:
            FunctionName: !Ref PutObjectTagging

  InitialMD5Hash:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/initial_md5_hash/
      Handler: app.lambda_handler
      Runtime: python3.8

  IntermediateMD5Hash:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/intermediate_md5_hash/
      Handler: app.lambda_handler
      Runtime: python3.8

  PutObjectTagging:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/put_object_tagging/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  S3MD5HashStateMachineArn:
    Description: Stock Trading State machine ARN
    Value: !Ref S3MD5HashStateMachine
  S3MD5HashStateMachineRoleArn:
    Description: IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates
    Value: !GetAtt S3MD5HashStateMachineRole.Arn
