---
version: 2.1

py38: &py38
  docker:
    - image: cimg/python:3.8.9

cache_tox_envs: &cache_tox_envs
  save_cache:
    key: >-
      {{ checksum "tox.ini" }}
      {{ checksum "functions/initial_md5_hash/requirements.txt" }}
      {{ checksum "functions/intermediate_md5_hash/requirements.txt" }}
      {{ checksum "functions/put_object_tagging/requirements.txt" }}
    paths:
      - .tox

commands:
  run_tox:
    description: Install and run tox with a given environment
    parameters:
      toxenv:
        description: The name of the environment as per tox.ini, e.g. py38 or lint
        type: string
      extra_args:
        description: Extra arguments that are consumed only when running pytest
        type: string
        default: ''
    steps:
      - run: pip install tox
      - run: tox -e << parameters.toxenv >> -- << parameters.extra_args >>

jobs:
  lint:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: lint
      - *cache_tox_envs

  unit_tests:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: py38
          extra_args: -k unit
      - *cache_tox_envs

  integration_tests:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: py38
          extra_args: -k integration
      - *cache_tox_envs

  coverage_report:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: coverage-report
      - *cache_tox_envs

workflows:
  version: 2
  build_workflow:
    jobs:
      - lint
      - coverage_report
      - unit_tests
